#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 	-d I II III IV V
bspc monitor HDMI-A-0 		-d VI VII VIII IX X

bspc config border_width	2
bspc config window_gap          0
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config normal_border_color	'#0000FF'
bspc config active_border_color	'#00FF00'
bspc config focused_border_color '#FF0000'

bspc rule -a URxvt:urxvt_keys_help state=floating
